# Generated by Django 5.1.6 on 2026-03-10 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.project')),
            ],
            options={
                'db_table': 'project_roles',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
