# Generated by Django 5.1.6 on 2026-05-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alert_project_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expense_project_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expense_project_category_idx',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
